version: "3.8"

services:
  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=Recysell-V1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: postgresql-spring
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-spring
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build: ./recysell
    container_name: recysell
    ports:
      - "8080:8080"
    environment:
      - SECRET=${SECRET}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    depends_on:
      pg:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./recysell/uploads:/app/uploads

  front:
    build: ./front-recysell
    container_name: front-recysell
    ports:
      - "4200:4200"
    depends_on:
      - app
    restart: on-failure

volumes:
  pgdata:
  pgadmin-data: